site_name: plassembler
site_url: "https://github.com/gbouras13/plassembler"
site_author: George Bouras
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - shell
        - python
nav:
    - ABOUT:
      - Overview: index.md
      - Why Use Plassembler?: reasons.md
      - Method: method.md
    - RUNNING:
      - Install: install.md
      - Usage: run.md
    - OUTPUT:
      - Output: output.md
    - BENCHMARKING:
      - Fastq Preparation: fastqs.md
      - Simulated Read Results: benchmarking_results_sim.md
      - Real Read Results: benchmarking_results_real.md
      - Flye Non Determinism: flye_non_determinism.md
    - OTHER FEATURES:
      - Quality Control: quality_control.md
      - Multiple Chromosomes: multiple_chromosome.md
      - Metagenomes: metagenomics.md

